const fs = require('fs');
const path = require('path');

// Puppy data
const puppies = [
  {
    "id": "sunny",
    "name": "Sunny",
    "breed": "Golden Retriever",
    "breedSlug": "golden-retriever",
    "price": 1200,
    "status": "available",
    "gender": "Male",
    "age": "8 weeks",
    "size": "Large",
    "location": "Budapest, Hungary",
    "description": "Playful, healthy, ready for a loving home. Great with kids!",
    "image": "https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=400&q=80",
    "featured": true
  },
  {
    "id": "bella",
    "name": "Bella",
    "breed": "Golden Retriever",
    "breedSlug": "golden-retriever",
    "price": 1300,
    "status": "reserved",
    "gender": "Female",
    "age": "10 weeks",
    "size": "Large",
    "location": "Budapest, Hungary",
    "description": "Gentle, affectionate, perfect for families.",
    "image": "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?auto=format&fit=crop&w=400&q=80",
    "featured": true
  },
  {
    "id": "charlie",
    "name": "Charlie",
    "breed": "Golden Retriever",
    "breedSlug": "golden-retriever",
    "price": 1250,
    "status": "available",
    "gender": "Male",
    "age": "9 weeks",
    "size": "Large",
    "location": "Debrecen, Hungary",
    "description": "Energetic and friendly, loves to play fetch. Excellent temperament.",
    "image": "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=400&q=80",
    "featured": false
  },
  {
    "id": "max",
    "name": "Max",
    "breed": "French Bulldog",
    "breedSlug": "french-bulldog",
    "price": 1500,
    "status": "available",
    "gender": "Male",
    "age": "12 weeks",
    "size": "Small",
    "location": "Budapest, Hungary",
    "description": "Playful, adaptable, and smart companion. Great for apartments.",
    "image": "https://images.unsplash.com/photo-1518715308788-3005759c61d3?auto=format&fit=crop&w=400&q=80",
    "featured": false
  },
  {
    "id": "luna",
    "name": "Luna",
    "breed": "French Bulldog",
    "breedSlug": "french-bulldog",
    "price": 1600,
    "status": "available",
    "gender": "Female",
    "age": "10 weeks",
    "size": "Small",
    "location": "Szeged, Hungary",
    "description": "Sweet and calm personality, loves cuddles and gentle play.",
    "image": "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=400&q=80",
    "featured": true
  },
  {
    "id": "rocky",
    "name": "Rocky",
    "breed": "French Bulldog",
    "breedSlug": "french-bulldog",
    "price": 1550,
    "status": "sold",
    "gender": "Male",
    "age": "14 weeks",
    "size": "Small",
    "location": "Pécs, Hungary",
    "description": "Confident and playful, great with children and other pets.",
    "image": "https://images.unsplash.com/photo-1605568427561-40dd23c2acea?auto=format&fit=crop&w=400&q=80",
    "featured": false
  },
  {
    "id": "mimi",
    "name": "Mimi",
    "breed": "Pomeranian",
    "breedSlug": "pomeranian",
    "price": 1100,
    "status": "available",
    "gender": "Female",
    "age": "8 weeks",
    "size": "Toy",
    "location": "Budapest, Hungary",
    "description": "Tiny but brave, fluffy and adorable. Perfect lap dog.",
    "image": "https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=400&q=80",
    "featured": true
  },
  {
    "id": "teddy",
    "name": "Teddy",
    "breed": "Pomeranian",
